"""Regenerate a MEMORY.md-style index from Postgres topics."""
from __future__ import annotations

from pathlib import Path

from khipu.db import connect


def regen_memory_md(out_path: Path, *, limit: int = 200) -> int:
    lines = [
        "# Memory — Conversation Wiki (from Khipu PG)",
        "",
        "_Generated by `khipu regen-memory`. Dual-run: legacy files remain SoT for writes until P3._",
        "",
        "## Topics (recent)",
        "",
    ]
    n = 0
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT slug, COALESCE(title, slug), status, updated_at
                FROM topics
                WHERE deleted_at IS NULL
                ORDER BY updated_at DESC NULLS LAST
                LIMIT %s
                """,
                (limit,),
            )
            for slug, title, status, updated in cur.fetchall():
                lines.append(
                    f"- [{title}](topics/{slug}.md) — status={status}; updated={updated}"
                )
                n += 1
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Write-then-rename: a crash or a full disk partway through a direct write
    # would leave the index truncated, and this file is what a human reads to
    # find a topic.
    tmp = out_path.with_name(out_path.name + ".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(out_path)
    return n
